create table users (
  user_id                bigint(20) unsigned not null auto_increment,
  user_registered        timestamp not null default current_timestamp,
  user_email             varchar(100),
  user_screenname        varchar(100),
  user_md5pass           varchar(64),
  user_key               varchar(64),
  user_country           varchar(40),
  user_aboutyou          text,
  user_email_validated   int(1) unsigned default 0,
  user_wants_emails      int(1) unsigned default 1,
  user_icon              varchar(160),
  user_icon_height       int(8) unsigned,
  user_icon_width        int(8) unsigned,
  user_comments          int(8) unsigned,
  user_likes             int(8) unsigned,
  user_dislikes          int(8) unsigned,
  user_friends           int(8) unsigned,
  user_followers         int(8) unsigned,
  user_ignoredby         int(8) unsigned,
  user_credibility       int(8) unsigned,
  user_last_comment_ip   varchar(16),
  user_last_comment_time datetime,
  primary key                       (user_id),
  unique  key user_email_index      (user_email),
  unique  key user_key_index        (user_key),
  unique  key user_screenname_index (user_screenname),
          key user_comments_index   (user_comments),
          key last_comment_ip_index (user_last_comment_ip)
);
